[package]
name = "readchat"
version = "0.2.1"
authors = ["museun <museun@outlook.com>"]
edition = "2018"
license = "Unlicense"
build = "build.rs"

[dependencies]
anyhow               = "1.0.32"

crossterm            = { version = "0.18.0", features = ["event-stream"] }
fastrand             = "1.3.5"
pico-args            = "0.3.4"

unicode-segmentation = "1.6.0"
unicode-width        = "0.1.8"

twitchchat           = { version = "0.14.4", features = ["async", "async-io"] } 

async-executor       = "1.3.0"
futures-lite         = "1.8.0"
pin-project-lite     = "0.1.10"

# crossbeam-channel = "0.4.4"
