[package]
name = "readchat"
version = "0.1.0"
authors = ["museun <museun@outlook.com>"]
edition = "2018"
license = "Unlicense"

[dependencies]
twitchchat = { version = "0.7.0" }
crossbeam-channel = "0.3.9"
unicode-width = "0.1.5"
unicode-segmentation = "1.3.0"
crossterm = "0.10.1" # barely used
yansi = "0.5.0"
