[package]
name = "readchat"
version = "0.3.0"
authors = ["museun <museun@outlook.com>"]
edition = "2018"
license = "Unlicense"
build = "build.rs"

[dependencies]
anyhow               = "1.0.32"
crossbeam-channel    = "0.4.4"
crossterm            = "0.18.0"
fastrand             = "1.3.5"
pico-args            = "0.3.4"
twitchchat           = "0.14.4"
unicode-segmentation = "1.6.0"
unicode-width        = "0.1.8"
