[package]
name = "readchat"
version = "0.1.2"
authors = ["museun <museun@outlook.com>"]
edition = "2018"
license = "Unlicense"

[dependencies]
twitchchat = "0.7.2"
crossbeam-channel = "0.3.9"
unicode-width = "0.1.5"
unicode-segmentation = "1.3.0"

# ensure ANSI escape sequences will be processed
clicolors-control = "1.0.0"
# get the console size
console = "0.7.7"
# draw colored strings
yansi = "0.5.0"
# catch SIGQUIT / Ctrl+C 
ctrlc = "3.1.3"
